In [8]:
import numpy as np

In [9]:
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
twitter_data = pd.read_csv('result.csv')

In [11]:
plt.figure()

In [12]:
twitter_data.friends

0      931
1      443
2       22
3      380
4      947
5     1940
6      328
7     3609
8      711
9      155
10     153
11      88
12     534
13    2115
14     221
15     111
16     221
17     221
18    1309
19     241
20     210
21    5478
22    5070
23    4977
24     221
25      12
26     295
27    3145
28    1078
29     866
30    5882
31     866
32    1929
33     978
34    1986
35     588
36    2735
37     910
38    3066
39     221
40     126
41    1986
42     212
43     724
44    1121
45     221
46     159
47     687
48     221
49    1531
Name: friends, dtype: int64

In [13]:
hist1,edges1 = np.histogram(twitter_data.friends)

In [18]:
plt.bar(edges1[:-1],hist1,width=edges1[1:]-edges1[:-1])

<Container object of 10 artists>

In [15]:
hist1

array([24, 11,  2,  5,  1,  2,  1,  0,  2,  2], dtype=int64)

In [16]:
edges1

array([   12.,   599.,  1186.,  1773.,  2360.,  2947.,  3534.,  4121.,
        4708.,  5295.,  5882.])

In [17]:
plt.scatter(twitter_data.followers,twitter_data.retwc)

In [19]:
edges1[:-1]

array([   12.,   599.,  1186.,  1773.,  2360.,  2947.,  3534.,  4121.,
        4708.,  5295.])

In [20]:
edges1[1:]

array([  599.,  1186.,  1773.,  2360.,  2947.,  3534.,  4121.,  4708.,
        5295.,  5882.])

In [21]:
twitter_data.corr()

retwc  followers   friends
retwc      1.000000  -0.075010 -0.057119
followers -0.075010   1.000000  0.033054
friends   -0.057119   0.033054  1.000000

In [23]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm

In [24]:
twitter_data = pd.read_csv('result.csv')

plt.figure()
hist1,edges1 = np.histogram(twitter_data.friends)
plt.bar(edges1[:-1],hist1,width=edges1[1:]-edges1[:-1])

plt.scatter(twitter_data.followers,twitter_data.retwc)
plt.scatter(twitter_data.followers,twitter_data.friends)
y = twitter_data.friends
X = twitter_data.followers
X = sm.add_constant(X)

In [25]:
lr_model = sm.OLS(y,X).fit()

In [26]:
print(lr_model.summary())

                            OLS Regression Results                            
Dep. Variable:                friends   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.020
Method:                 Least Squares   F-statistic:                   0.05250
Date:                Mon, 13 Mar 2017   Prob (F-statistic):              0.820
Time:                        11:15:12   Log-Likelihood:                -436.51
No. Observations:                  50   AIC:                             877.0
Df Residuals:                      48   BIC:                             880.8
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
const       1227.4454    227.323      5.400      0.0

In [28]:
X_prime = np.linspace(X.followers.min(),X.followers.max(),100)

In [29]:
X_prime = sm.add_constant(X_prime)

In [30]:
y_hat = lr_model.predict(X_prime)

In [31]:
plt.scatter(X.followers,y)

In [32]:
plt.xlabel("followers")

In [34]:
plt.ylabel("friends")






In [35]:
plt.plot(X_prime[:,1],y_hat)